name: Tests
on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-22.04
        steps:
            ###################################################
            #
            # Prepare
            #
            ###################################################

            - name: (PREPARE) Checkout Repository
              uses: actions/checkout@v3
              with:
                  lfs: true

            - name: (PREPARE) Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 22
                  cache: yarn

            - name: (PREPARE) Install Node Modules
              run: yarn

            ###################################################
            #
            # Test
            #
            ###################################################

            - name: (TEST) Check ESLint
              run: yarn lint

            - name: (TEST) Check Prettier
              run: yarn format
